name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build MpdelInfService and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Build image
      run: |
        minikube image build -f ./ModelInfService/Dockerfile -t aadilminhaz/modelinf-service:v1 .
    - name: Deploy to minikube
      run:
        kubectl apply -f deploy/modelinf-service-k8s.yaml
    - name: Checking Deployment..
      run: kubectl wait --for=condition=ready pod -l app=modelinf-service
    - name: Checking Deployment..
      run: kubectl get pods -A
    - name: Test service URLs
      run: |
        minikube service list
        minikube service modelinf-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service modelinf-service --url)
